export default {
    Binance: {
        spot: [
            "0G",
            "1000CAT",
            "1000CHEEMS",
            "1000SATS",
            "1INCH",
            "1MBABYDOGE",
            "2Z",
            "A",
            "A2Z",
            "AAVE",
            "ACE",
            "ACH",
            "ACT",
            "ACX",
            "ADA",
            "AEVO",
            "AGLD",
            "AI",
            "AIXBT",
            "ALGO",
            "ALICE",
            "ALPINE",
            "ALT",
            "ANIME",
            "ANKR",
            "APE",
            "API3",
            "APT",
            "AR",
            "ARB",
            "ARK",
            "ARKM",
            "ARPA",
            "ASR",
            "ASTER",
            "ASTR",
            "ATA",
            "ATOM",
            "AUCTION",
            "AUDIO",
            "AVA",
            "AVAX",
            "AVNT",
            "AWE",
            "AXL",
            "AXS",
            "BABY",
            "BANANA",
            "BANANAS31",
            "BAND",
            "BARD",
            "BAT",
            "BB",
            "BCH",
            "BEAMX",
            "BEL",
            "BERA",
            "BICO",
            "BIGTIME",
            "BIO",
            "BLUR",
            "BMT",
            "BNB",
            "BNT",
            "BOME",
            "BONK",
            "BROCCOLI714",
            "BTC",
            "C",
            "C98",
            "CAKE",
            "CATI",
            "CELO",
            "CELR",
            "CETUS",
            "CFX",
            "CGPT",
            "CHESS",
            "CHR",
            "CHZ",
            "CKB",
            "COMP",
            "COOKIE",
            "COS",
            "COTI",
            "COW",
            "CRV",
            "CTK",
            "CTSI",
            "CVC",
            "CVX",
            "CYBER",
            "D",
            "DASH",
            "DEGO",
            "DENT",
            "DEXE",
            "DF",
            "DGB",
            "DIA",
            "DOGE",
            "DOGS",
            "DOLO",
            "DOT",
            "DUSK",
            "DYDX",
            "DYM",
            "EDEN",
            "EDU",
            "EGLD",
            "EIGEN",
            "ENA",
            "ENJ",
            "ENS",
            "ENSO",
            "EPIC",
            "ERA",
            "ETC",
            "ETH",
            "ETHFI",
            "EUL",
            "F",
            "FET",
            "FF",
            "FIDA",
            "FIL",
            "FIO",
            "FIS",
            "FLM",
            "FLOKI",
            "FLOW",
            "FLUX",
            "FORM",
            "FORTH",
            "FUN",
            "FXS",
            "G",
            "GALA",
            "GAS",
            "GHST",
            "GIGGLE",
            "GLM",
            "GLMR",
            "GMT",
            "GMX",
            "GPS",
            "GRT",
            "GTC",
            "GUN",
            "HAEDAL",
            "HBAR",
            "HEI",
            "HEMI",
            "HFT",
            "HIGH",
            "HIVE",
            "HMSTR",
            "HOLO",
            "HOME",
            "HOOK",
            "HOT",
            "HUMA",
            "HYPER",
            "ICP",
            "ICX",
            "ID",
            "IDEX",
            "ILV",
            "IMX",
            "INIT",
            "INJ",
            "IO",
            "IOST",
            "IOTA",
            "IOTX",
            "JASMY",
            "JOE",
            "JST",
            "JTO",
            "JUP",
            "KAIA",
            "KAITO",
            "KAVA",
            "KDA",
            "KERNEL",
            "KMNO",
            "KNC",
            "KSM",
            "LA",
            "LAYER",
            "LDO",
            "LINEA",
            "LINK",
            "LISTA",
            "LPT",
            "LQTY",
            "LRC",
            "LSK",
            "LTC",
            "LUMIA",
            "LUNA",
            "LUNC",
            "MAGIC",
            "MANA",
            "MANTA",
            "MASK",
            "MAV",
            "MBOX",
            "ME",
            "MEME",
            "METIS",
            "MINA",
            "MIRA",
            "MITO",
            "MLN",
            "MORPHO",
            "MOVE",
            "MOVR",
            "MTL",
            "MUBARAK",
            "NEAR",
            "NEIRO",
            "NEO",
            "NEWT",
            "NFP",
            "NIL",
            "NKN",
            "NMR",
            "NOM",
            "NOT",
            "NTRN",
            "NXPC",
            "OG",
            "OGN",
            "OM",
            "ONDO",
            "ONE",
            "ONG",
            "ONT",
            "OP",
            "OPEN",
            "ORCA",
            "ORDI",
            "OXT",
            "PARTI",
            "PAXG",
            "PENDLE",
            "PENGU",
            "PEOPLE",
            "PEPE",
            "PERP",
            "PHA",
            "PHB",
            "PIXEL",
            "PLUME",
            "PNUT",
            "POL",
            "POLYX",
            "PORTAL",
            "POWR",
            "PROM",
            "PROVE",
            "PUMP",
            "PUNDIX",
            "PYTH",
            "QNT",
            "QTUM",
            "QUICK",
            "RAD",
            "RARE",
            "RAY",
            "RDNT",
            "RED",
            "REI",
            "RENDER",
            "RESOLV",
            "REZ",
            "RIF",
            "RLC",
            "RONIN",
            "ROSE",
            "RPL",
            "RSR",
            "RUNE",
            "RVN",
            "S",
            "SAGA",
            "SAHARA",
            "SAND",
            "SANTOS",
            "SC",
            "SCR",
            "SCRT",
            "SEI",
            "SFP",
            "SHELL",
            "SHIB",
            "SIGN",
            "SKL",
            "SKY",
            "SLP",
            "SNX",
            "SOL",
            "SOLV",
            "SOMI",
            "SOPH",
            "SPELL",
            "SPK",
            "SSV",
            "STEEM",
            "STG",
            "STO",
            "STORJ",
            "STRK",
            "STX",
            "SUI",
            "SUN",
            "SUPER",
            "SUSHI",
            "SXP",
            "SXT",
            "SYN",
            "SYRUP",
            "SYS",
            "T",
            "TAO",
            "THE",
            "THETA",
            "TIA",
            "TLM",
            "TNSR",
            "TON",
            "TOWNS",
            "TRB",
            "TREE",
            "TRU",
            "TRUMP",
            "TRX",
            "TST",
            "TURBO",
            "TURTLE",
            "TUT",
            "TWT",
            "UMA",
            "UNI",
            "USDC",
            "USTC",
            "USUAL",
            "VANA",
            "VANRY",
            "VELODROME",
            "VET",
            "VIC",
            "VIRTUAL",
            "VOXEL",
            "VTHO",
            "W",
            "WAL",
            "WAXP",
            "WCT",
            "WIF",
            "WLD",
            "WLFI",
            "WOO",
            "XAI",
            "XLM",
            "XNO",
            "XPL",
            "XRP",
            "XTZ",
            "XVG",
            "XVS",
            "YB",
            "YFI",
            "YGG",
            "ZBT",
            "ZEC",
            "ZEN",
            "ZIL",
            "ZK",
            "ZKC",
            "ZRO",
            "ZRX"
        ],
        future: [
            "0G",
            "1000CAT",
            "1000CHEEMS",
            "1000SATS",
            "1INCH",
            "1MBABYDOGE",
            "2Z",
            "A",
            "A2Z",
            "AAVE",
            "ACE",
            "ACH",
            "ACT",
            "ACX",
            "ADA",
            "AERGO",
            "AERO",
            "AEVO",
            "AGLD",
            "AI",
            "AI16Z",
            "AIA",
            "AIN",
            "AIO",
            "AIOT",
            "AIXBT",
            "AKE",
            "AKT",
            "ALCH",
            "ALGO",
            "ALICE",
            "ALPINE",
            "ALT",
            "ANIME",
            "ANKR",
            "APE",
            "API3",
            "APT",
            "AR",
            "ARB",
            "ARC",
            "ARIA",
            "ARK",
            "ARKM",
            "ARPA",
            "ASR",
            "ASTER",
            "ASTR",
            "ATA",
            "ATH",
            "ATOM",
            "AUCTION",
            "AVA",
            "AVAAI",
            "AVAX",
            "AVNT",
            "AWE",
            "AXL",
            "AXS",
            "B",
            "B2",
            "B3",
            "BABY",
            "BAN",
            "BANANA",
            "BANANAS31",
            "BAND",
            "BANK",
            "BARD",
            "BAS",
            "BAT",
            "BB",
            "BCH",
            "BDXN",
            "BEAMX",
            "BEL",
            "BERA",
            "BICO",
            "BID",
            "BIGTIME",
            "BIO",
            "BLESS",
            "BLUAI",
            "BLUR",
            "BMT",
            "BNB",
            "BNT",
            "BOME",
            "BR",
            "BRETT",
            "BROCCOLI714",
            "BSV",
            "BTC",
            "BTR",
            "C",
            "C98",
            "CAKE",
            "CARV",
            "CATI",
            "CELO",
            "CELR",
            "CETUS",
            "CFX",
            "CGPT",
            "CHESS",
            "CHILLGUY",
            "CHR",
            "CHZ",
            "CKB",
            "COAI",
            "COMMON",
            "COMP",
            "COOKIE",
            "COS",
            "COTI",
            "COW",
            "CROSS",
            "CRV",
            "CTK",
            "CTSI",
            "CUDIS",
            "CVC",
            "CVX",
            "CYBER",
            "D",
            "DASH",
            "DEEP",
            "DEGEN",
            "DEGO",
            "DENT",
            "DEXE",
            "DF",
            "DIA",
            "DMC",
            "DOGE",
            "DOGS",
            "DOLO",
            "DOOD",
            "DOT",
            "DRIFT",
            "DUSK",
            "DYDX",
            "DYM",
            "EDEN",
            "EDU",
            "EGLD",
            "EIGEN",
            "ENA",
            "ENJ",
            "ENS",
            "ENSO",
            "EPIC",
            "EPT",
            "ERA",
            "ESPORTS",
            "ETC",
            "ETH",
            "ETHFI",
            "ETHW",
            "EUL",
            "EVAA",
            "F",
            "FARTCOIN",
            "FET",
            "FF",
            "FHE",
            "FIDA",
            "FIL",
            "FIO",
            "FIS",
            "FLM",
            "FLOCK",
            "FLOW",
            "FLUID",
            "FLUX",
            "FORM",
            "FORTH",
            "FUN",
            "FXS",
            "G",
            "GALA",
            "GAS",
            "GHST",
            "GIGGLE",
            "GLM",
            "GMT",
            "GMX",
            "GOAT",
            "GPS",
            "GRASS",
            "GRIFFAIN",
            "GRT",
            "GTC",
            "GUN",
            "H",
            "HAEDAL",
            "HANA",
            "HBAR",
            "HEI",
            "HEMI",
            "HFT",
            "HIGH",
            "HIPPO",
            "HIVE",
            "HMSTR",
            "HOLO",
            "HOME",
            "HOOK",
            "HOT",
            "HUMA",
            "HYPE",
            "HYPER",
            "ICNT",
            "ICP",
            "ICX",
            "ID",
            "IDOL",
            "ILV",
            "IMX",
            "IN",
            "INIT",
            "INJ",
            "IO",
            "IOST",
            "IOTA",
            "IOTX",
            "IP",
            "JASMY",
            "JELLYJELLY",
            "JOE",
            "JST",
            "JTO",
            "JUP",
            "KAIA",
            "KAITO",
            "KAS",
            "KAVA",
            "KDA",
            "KERNEL",
            "KGEN",
            "KMNO",
            "KNC",
            "KOMA",
            "KSM",
            "LA",
            "LAB",
            "LAYER",
            "LDO",
            "LIGHT",
            "LINEA",
            "LINK",
            "LISTA",
            "LPT",
            "LQTY",
            "LRC",
            "LSK",
            "LTC",
            "LUMIA",
            "M",
            "MAGIC",
            "MANA",
            "MANTA",
            "MASK",
            "MAV",
            "MAVIA",
            "MBOX",
            "ME",
            "MELANIA",
            "MEME",
            "MERL",
            "MET",
            "METIS",
            "MEW",
            "MILK",
            "MINA",
            "MIRA",
            "MITO",
            "MLN",
            "MOCA",
            "MOODENG",
            "MORPHO",
            "MOVE",
            "MOVR",
            "MTL",
            "MUBARAK",
            "MYRO",
            "MYX",
            "NAORIS",
            "NEAR",
            "NEIRO",
            "NEO",
            "NEWT",
            "NFP",
            "NIL",
            "NKN",
            "NMR",
            "NOM",
            "NOT",
            "NTRN",
            "NXPC",
            "OBOL",
            "OG",
            "OGN",
            "OL",
            "OM",
            "ON",
            "ONDO",
            "ONE",
            "ONG",
            "ONT",
            "OP",
            "OPEN",
            "ORCA",
            "ORDER",
            "ORDI",
            "OXT",
            "PARTI",
            "PAXG",
            "PENDLE",
            "PENGU",
            "PEOPLE",
            "PERP",
            "PHA",
            "PHB",
            "PIPPIN",
            "PIXEL",
            "PLUME",
            "PNUT",
            "POL",
            "POLYX",
            "PONKE",
            "POPCAT",
            "PORT3",
            "PORTAL",
            "POWR",
            "PROM",
            "PROMPT",
            "PROVE",
            "PTB",
            "PUFFER",
            "PUMP",
            "PUMPBTC",
            "PUNDIX",
            "PYTH",
            "Q",
            "QNT",
            "QTUM",
            "QUICK",
            "RARE",
            "RDNT",
            "RECALL",
            "RED",
            "REI",
            "RENDER",
            "RESOLV",
            "REZ",
            "RIF",
            "RLC",
            "RONIN",
            "ROSE",
            "RPL",
            "RSR",
            "RUNE",
            "RVN",
            "RVV",
            "S",
            "SAFE",
            "SAGA",
            "SAHARA",
            "SAND",
            "SANTOS",
            "SAPIEN",
            "SCR",
            "SCRT",
            "SEI",
            "SFP",
            "SHELL",
            "SIGN",
            "SIREN",
            "SKATE",
            "SKL",
            "SKY",
            "SKYAI",
            "SLP",
            "SNX",
            "SOL",
            "SOLV",
            "SOMI",
            "SONIC",
            "SOON",
            "SOPH",
            "SPELL",
            "SPK",
            "SPX",
            "SQD",
            "SSV",
            "STBL",
            "STEEM",
            "STG",
            "STO",
            "STORJ",
            "STRK",
            "STX",
            "SUI",
            "SUN",
            "SUPER",
            "SUSHI",
            "SWARMS",
            "SWELL",
            "SXP",
            "SXT",
            "SYN",
            "SYRUP",
            "SYS",
            "T",
            "TA",
            "TAG",
            "TAIKO",
            "TAKE",
            "TANSSI",
            "TAO",
            "THE",
            "THETA",
            "TIA",
            "TLM",
            "TNSR",
            "TOKEN",
            "TON",
            "TOSHI",
            "TOWNS",
            "TRB",
            "TREE",
            "TRU",
            "TRUMP",
            "TRX",
            "TST",
            "TURBO",
            "TURTLE",
            "TUT",
            "TWT",
            "UB",
            "UMA",
            "UNI",
            "USDC",
            "USELESS",
            "USTC",
            "USUAL",
            "VANA",
            "VANRY",
            "VELODROME",
            "VELVET",
            "VET",
            "VFY",
            "VIC",
            "VINE",
            "VIRTUAL",
            "VOXEL",
            "VTHO",
            "VVV",
            "W",
            "WAL",
            "WAXP",
            "WCT",
            "WIF",
            "WLD",
            "WLFI",
            "WOO",
            "XAI",
            "XAN",
            "XCN",
            "XLM",
            "XNY",
            "XPIN",
            "XPL",
            "XRP",
            "XTZ",
            "XVG",
            "XVS",
            "YALA",
            "YB",
            "YFI",
            "YGG",
            "ZBT",
            "ZEC",
            "ZEN",
            "ZEREBRO",
            "ZETA",
            "ZIL",
            "ZK",
            "ZKC",
            "ZKJ",
            "ZORA",
            "ZRC",
            "ZRO",
            "ZRX"
        ]
    },
    Gate: {
        spot: [
            "0G",
            "1INCH",
            "2Z",
            "A",
            "A2Z",
            "A8",
            "AAPLX",
            "AAVE",
            "ACE",
            "ACH",
            "ACT",
            "ACX",
            "ADA",
            "AERGO",
            "AERO",
            "AEVO",
            "AGI",
            "AGLD",
            "AI",
            "AI16Z",
            "AIA",
            "AIN",
            "AIO",
            "AIOT",
            "AIOZ",
            "AIXBT",
            "AKE",
            "AKT",
            "ALCH",
            "ALEO",
            "ALGO",
            "ALICE",
            "ALPINE",
            "ALT",
            "AMZNX",
            "ANIME",
            "ANKR",
            "APE",
            "API3",
            "APT",
            "AR",
            "ARB",
            "ARC",
            "ARIA",
            "ARK",
            "ARKM",
            "ARPA",
            "ASP",
            "ASR",
            "ASTER",
            "ASTR",
            "ATA",
            "ATH",
            "ATOM",
            "AUCTION",
            "AUDIO",
            "AVA",
            "AVAAI",
            "AVAIL",
            "AVAX",
            "AVL",
            "AVNT",
            "AWE",
            "AXS",
            "B",
            "B2",
            "B3",
            "BABY",
            "BADGER",
            "BAN",
            "BANANA",
            "BANANAS31",
            "BAND",
            "BANK",
            "BARD",
            "BAS",
            "BAT",
            "BB",
            "BCH",
            "BDXN",
            "BEAMX",
            "BEL",
            "BERA",
            "BGSC",
            "BICO",
            "BID",
            "BIGTIME",
            "BIO",
            "BLAST",
            "BLESS",
            "BLUAI",
            "BLUR",
            "BMT",
            "BNB",
            "BNT",
            "BOBA",
            "BOME",
            "BONK",
            "BR",
            "BRETT",
            "BROCCOLI",
            "BSV",
            "BTC",
            "BTR",
            "C",
            "C98",
            "CAKE",
            "CAMP",
            "CARV",
            "CAT",
            "CATI",
            "CELO",
            "CELR",
            "CETUS",
            "CFX",
            "CGN",
            "CGPT",
            "CHEEMS",
            "CHESS",
            "CHILLGUY",
            "CHR",
            "CHZ",
            "CKB",
            "CLOUD",
            "COAI",
            "COINX",
            "COMMON",
            "COMP",
            "COOKIE",
            "CORE",
            "COS",
            "COTI",
            "COW",
            "CPOOL",
            "CRCLX",
            "CRO",
            "CROSS",
            "CRV",
            "CTC",
            "CTK",
            "CTSI",
            "CUDIS",
            "CVC",
            "CVX",
            "CYBER",
            "D",
            "DBR",
            "DEEP",
            "DEGEN",
            "DEGO",
            "DENT",
            "DEXE",
            "DF",
            "DFDVX",
            "DGB",
            "DIA",
            "DMC",
            "DOG",
            "DOGE",
            "DOGS",
            "DOLO",
            "DOOD",
            "DOT",
            "DRIFT",
            "DUSK",
            "DYDX",
            "DYM",
            "EDEN",
            "EDU",
            "EGLD",
            "EIGEN",
            "ELX",
            "ENA",
            "ENJ",
            "ENS",
            "ENSO",
            "EPIC",
            "EPT",
            "ERA",
            "ES",
            "ESPORTS",
            "ETC",
            "ETH",
            "ETHFI",
            "ETHW",
            "EUL",
            "EVAA",
            "F",
            "FARTCOIN",
            "FET",
            "FF",
            "FHE",
            "FIDA",
            "FIL",
            "FIO",
            "FIS",
            "FLK",
            "FLM",
            "FLOCK",
            "FLOKI",
            "FLOW",
            "FLR",
            "FLUID",
            "FLUX",
            "FORM",
            "FORTH",
            "FUN",
            "FWOG",
            "G",
            "GALA",
            "GAS",
            "GHST",
            "GIGGLE",
            "GLM",
            "GLMR",
            "GMT",
            "GMX",
            "GOAT",
            "GOOGLX",
            "GORK",
            "GPS",
            "GRASS",
            "GRIFFAIN",
            "GRT",
            "GT",
            "GUN",
            "H",
            "HAEDAL",
            "HANA",
            "HBAR",
            "HEI",
            "HEMI",
            "HFT",
            "HIFI",
            "HIGH",
            "HIPPO",
            "HIVE",
            "HMSTR",
            "HNT",
            "HOLO",
            "HOME",
            "HOODX",
            "HOOK",
            "HOT",
            "HUMA",
            "HYPE",
            "HYPER",
            "ICNT",
            "ICP",
            "ICX",
            "ID",
            "IDEX",
            "IDOL",
            "IKA",
            "ILV",
            "IMX",
            "IN",
            "INIT",
            "INJ",
            "IO",
            "IOST",
            "IOTA",
            "IOTX",
            "IP",
            "JASMY",
            "JELLYJELLY",
            "JOE",
            "JST",
            "JTO",
            "JUP",
            "KAIA",
            "KAITO",
            "KAS",
            "KAVA",
            "KDA",
            "KERNEL",
            "KGEN",
            "KMNO",
            "KNC",
            "KOMA",
            "KSM",
            "LA",
            "LAB",
            "LAYER",
            "LDO",
            "LIGHT",
            "LINEA",
            "LINK",
            "LISTA",
            "LOOKS",
            "LPT",
            "LQTY",
            "LRC",
            "LSK",
            "LTC",
            "LUMIA",
            "LUNA",
            "LUNC",
            "M",
            "MAGIC",
            "MAJOR",
            "MANA",
            "MANTA",
            "MASK",
            "MAV",
            "MAVIA",
            "MBOX",
            "ME",
            "MELANIA",
            "MEME",
            "MERL",
            "MET",
            "METAX",
            "METIS",
            "MEW",
            "MILK",
            "MINA",
            "MIRA",
            "MITO",
            "MLN",
            "MNT",
            "MOCA",
            "MOG",
            "MOODENG",
            "MORPHO",
            "MOVE",
            "MOVR",
            "MSTRX",
            "MTL",
            "MUBARAK",
            "MYRO",
            "MYX",
            "NAORIS",
            "NAVX",
            "NEAR",
            "NEIROCTO",
            "NEO",
            "NEWT",
            "NFP",
            "NIL",
            "NKN",
            "NMR",
            "NODE",
            "NOM",
            "NOT",
            "NTRN",
            "NVDAX",
            "NXPC",
            "OBOL",
            "OG",
            "OGN",
            "OKB",
            "OL",
            "OM",
            "ON",
            "ONDO",
            "ONE",
            "ONG",
            "ONT",
            "OP",
            "OPEN",
            "ORCA",
            "ORDER",
            "ORDI",
            "OXT",
            "P",
            "PARTI",
            "PAXG",
            "PEAQ",
            "PENDLE",
            "PENGU",
            "PEOPLE",
            "PEPE",
            "PERP",
            "PHA",
            "PHB",
            "PI",
            "PIPPIN",
            "PIXEL",
            "PLUME",
            "PNUT",
            "POL",
            "POLYX",
            "PONKE",
            "POPCAT",
            "PORT3",
            "PORTAL",
            "POWR",
            "PRCL",
            "PROM",
            "PROMPT",
            "PROVE",
            "PTB",
            "PUFFER",
            "PUMP",
            "PUMPBTC",
            "PUNDIX",
            "PYTH",
            "Q",
            "QNT",
            "QQQX",
            "QTUM",
            "QUBIC",
            "QUICK",
            "RAD",
            "RARE",
            "RATS",
            "RAY",
            "RDNT",
            "RECALL",
            "REI",
            "RENDER",
            "RESOLV",
            "REX",
            "REZ",
            "RHEA",
            "RIF",
            "RLC",
            "RON",
            "ROSE",
            "RPL",
            "RSR",
            "RUNE",
            "RVN",
            "RVV",
            "S",
            "SAFE",
            "SAGA",
            "SAHARA",
            "SAND",
            "SANTOS",
            "SAPIEN",
            "SATS",
            "SC",
            "SCA",
            "SCR",
            "SCRT",
            "SD",
            "SEI",
            "SFP",
            "SHELL",
            "SHIB",
            "SIGN",
            "SIREN",
            "SKATE",
            "SKL",
            "SKY",
            "SKYAI",
            "SLP",
            "SNT",
            "SNX",
            "SOL",
            "SOLV",
            "SOMI",
            "SONIC",
            "SOON",
            "SOPH",
            "SPELL",
            "SPK",
            "SPX",
            "SPYX",
            "SQD",
            "SSV",
            "STBL",
            "STEEM",
            "STG",
            "STO",
            "STORJ",
            "STRK",
            "STX",
            "SUI",
            "SUN",
            "SUNDOG",
            "SUPER",
            "SUSHI",
            "SWARMS",
            "SWEAT",
            "SWELL",
            "SWTCH",
            "SXP",
            "SXT",
            "SYN",
            "SYRUP",
            "SYS",
            "T",
            "TA",
            "TAG",
            "TAI",
            "TAIKO",
            "TAKE",
            "TANSSI",
            "TAO",
            "THE",
            "THETA",
            "TIA",
            "TLM",
            "TNSR",
            "TOKEN",
            "TON",
            "TOSHI",
            "TOWNS",
            "TQQQX",
            "TRB",
            "TREE",
            "TRU",
            "TRUMP",
            "TRX",
            "TSLAX",
            "TST",
            "TSTBSC",
            "TURBO",
            "TURTLE",
            "TUT",
            "TWT",
            "U",
            "UB",
            "UMA",
            "UNI",
            "USDC",
            "USELESS",
            "USTC",
            "USUAL",
            "VANA",
            "VANRY",
            "VELO",
            "VELODROME",
            "VELVET",
            "VET",
            "VFY",
            "VIC",
            "VINE",
            "VIRTUAL",
            "VOXEL",
            "VTHO",
            "VVV",
            "W",
            "WAL",
            "WAVES",
            "WAXP",
            "WCT",
            "WIF",
            "WLD",
            "WLFI",
            "WOO",
            "X",
            "XAI",
            "XAN",
            "XAUT",
            "XCH",
            "XCN",
            "XDC",
            "XION",
            "XLM",
            "XNY",
            "XPIN",
            "XPL",
            "XRP",
            "XTZ",
            "XVS",
            "YALA",
            "YB",
            "YFI",
            "YGG",
            "YZY",
            "ZBCN",
            "ZBT",
            "ZEREBRO",
            "ZETA",
            "ZEUS",
            "ZIL",
            "ZK",
            "ZKC",
            "ZKJ",
            "ZORA",
            "ZRC",
            "ZRO",
            "ZRX"
        ],
        future: [
            "0G",
            "1INCH",
            "2Z",
            "A",
            "A2Z",
            "A8",
            "AAPLX",
            "AAVE",
            "ACE",
            "ACH",
            "ACT",
            "ACX",
            "ADA",
            "AERGO",
            "AERO",
            "AEVO",
            "AGI",
            "AGLD",
            "AI",
            "AI16Z",
            "AIA",
            "AIN",
            "AIO",
            "AIOT",
            "AIOZ",
            "AIXBT",
            "AKE",
            "AKT",
            "ALCH",
            "ALEO",
            "ALGO",
            "ALICE",
            "ALPINE",
            "ALT",
            "AMZNX",
            "ANIME",
            "ANKR",
            "APE",
            "API3",
            "APT",
            "AR",
            "ARB",
            "ARC",
            "ARIA",
            "ARK",
            "ARKM",
            "ARPA",
            "ASP",
            "ASR",
            "ASTER",
            "ASTR",
            "ATH",
            "ATOM",
            "AUCTION",
            "AUDIO",
            "AVA",
            "AVAAI",
            "AVAIL",
            "AVAX",
            "AVL",
            "AVNT",
            "AWE",
            "AXS",
            "B",
            "B2",
            "B3",
            "BABY",
            "BADGER",
            "BAN",
            "BANANA",
            "BANANAS31",
            "BAND",
            "BANK",
            "BARD",
            "BAS",
            "BAT",
            "BB",
            "BCH",
            "BDXN",
            "BEAMX",
            "BEL",
            "BERA",
            "BGSC",
            "BICO",
            "BID",
            "BIGTIME",
            "BIO",
            "BLAST",
            "BLESS",
            "BLUAI",
            "BLUR",
            "BMT",
            "BNB",
            "BNT",
            "BOBA",
            "BOME",
            "BONK",
            "BR",
            "BRETT",
            "BROCCOLI",
            "BSV",
            "BTC",
            "BTR",
            "C",
            "C98",
            "CAKE",
            "CAMP",
            "CARV",
            "CAT",
            "CATI",
            "CELO",
            "CELR",
            "CETUS",
            "CFX",
            "CGN",
            "CGPT",
            "CHEEMS",
            "CHESS",
            "CHILLGUY",
            "CHR",
            "CHZ",
            "CKB",
            "CLOUD",
            "COAI",
            "COINX",
            "COMMON",
            "COMP",
            "COOKIE",
            "CORE",
            "COS",
            "COTI",
            "COW",
            "CPOOL",
            "CRCLX",
            "CRO",
            "CROSS",
            "CRV",
            "CTC",
            "CTK",
            "CTSI",
            "CUDIS",
            "CVC",
            "CVX",
            "CYBER",
            "D",
            "DBR",
            "DEEP",
            "DEGEN",
            "DEGO",
            "DENT",
            "DEXE",
            "DF",
            "DFDVX",
            "DGB",
            "DIA",
            "DMC",
            "DOG",
            "DOGE",
            "DOGS",
            "DOLO",
            "DOOD",
            "DOT",
            "DRIFT",
            "DUSK",
            "DYDX",
            "DYM",
            "EDEN",
            "EDU",
            "EGLD",
            "EIGEN",
            "ELX",
            "ENA",
            "ENJ",
            "ENS",
            "ENSO",
            "EPIC",
            "EPT",
            "ERA",
            "ES",
            "ESPORTS",
            "ETC",
            "ETH",
            "ETHFI",
            "ETHW",
            "EUL",
            "EVAA",
            "F",
            "FARTCOIN",
            "FET",
            "FF",
            "FHE",
            "FIDA",
            "FIL",
            "FIO",
            "FIS",
            "FLK",
            "FLM",
            "FLOCK",
            "FLOKI",
            "FLOW",
            "FLR",
            "FLUID",
            "FLUX",
            "FORM",
            "FORTH",
            "FUN",
            "FWOG",
            "G",
            "GALA",
            "GAS",
            "GIGGLE",
            "GLM",
            "GLMR",
            "GMT",
            "GMX",
            "GOAT",
            "GOOGLX",
            "GORK",
            "GPS",
            "GRASS",
            "GRIFFAIN",
            "GRT",
            "GT",
            "GUN",
            "H",
            "HAEDAL",
            "HANA",
            "HBAR",
            "HEI",
            "HEMI",
            "HFT",
            "HIFI",
            "HIGH",
            "HIPPO",
            "HIVE",
            "HMSTR",
            "HNT",
            "HOLO",
            "HOME",
            "HOODX",
            "HOOK",
            "HOT",
            "HUMA",
            "HYPE",
            "HYPER",
            "ICNT",
            "ICP",
            "ICX",
            "ID",
            "IDEX",
            "IDOL",
            "IKA",
            "ILV",
            "IMX",
            "IN",
            "INIT",
            "INJ",
            "IO",
            "IOST",
            "IOTA",
            "IOTX",
            "IP",
            "JASMY",
            "JELLYJELLY",
            "JOE",
            "JST",
            "JTO",
            "JUP",
            "KAIA",
            "KAITO",
            "KAS",
            "KAVA",
            "KDA",
            "KERNEL",
            "KGEN",
            "KMNO",
            "KNC",
            "KOMA",
            "KSM",
            "LA",
            "LAB",
            "LAYER",
            "LDO",
            "LIGHT",
            "LINEA",
            "LINK",
            "LISTA",
            "LOOKS",
            "LPT",
            "LQTY",
            "LRC",
            "LSK",
            "LTC",
            "LUMIA",
            "LUNA",
            "LUNC",
            "M",
            "MAGIC",
            "MAJOR",
            "MANA",
            "MANTA",
            "MASK",
            "MAV",
            "MAVIA",
            "MBOX",
            "ME",
            "MELANIA",
            "MEME",
            "MERL",
            "MET",
            "METAX",
            "METIS",
            "MEW",
            "MINA",
            "MIRA",
            "MITO",
            "MNT",
            "MOCA",
            "MOG",
            "MOODENG",
            "MORPHO",
            "MOVE",
            "MOVR",
            "MSTRX",
            "MTL",
            "MUBARAK",
            "MYRO",
            "MYX",
            "NAORIS",
            "NAVX",
            "NEAR",
            "NEIROCTO",
            "NEO",
            "NEWT",
            "NFP",
            "NIL",
            "NKN",
            "NMR",
            "NODE",
            "NOM",
            "NOT",
            "NTRN",
            "NVDAX",
            "NXPC",
            "OBOL",
            "OG",
            "OGN",
            "OKB",
            "OL",
            "OM",
            "ON",
            "ONDO",
            "ONE",
            "ONG",
            "ONT",
            "OP",
            "OPEN",
            "ORCA",
            "ORDER",
            "ORDI",
            "OXT",
            "P",
            "PARTI",
            "PAXG",
            "PEAQ",
            "PENDLE",
            "PENGU",
            "PEOPLE",
            "PEPE",
            "PERP",
            "PHA",
            "PHB",
            "PI",
            "PIPPIN",
            "PIXEL",
            "PLUME",
            "PNUT",
            "POL",
            "POLYX",
            "PONKE",
            "POPCAT",
            "PORT3",
            "PORTAL",
            "POWR",
            "PRCL",
            "PROM",
            "PROMPT",
            "PROVE",
            "PTB",
            "PUFFER",
            "PUMP",
            "PUNDIX",
            "PYTH",
            "Q",
            "QNT",
            "QQQX",
            "QTUM",
            "QUBIC",
            "QUICK",
            "RAD",
            "RARE",
            "RATS",
            "RAY",
            "RDNT",
            "RECALL",
            "REI",
            "RENDER",
            "RESOLV",
            "REX",
            "REZ",
            "RHEA",
            "RIF",
            "RLC",
            "RON",
            "ROSE",
            "RPL",
            "RSR",
            "RUNE",
            "RVN",
            "RVV",
            "S",
            "SAFE",
            "SAGA",
            "SAHARA",
            "SAND",
            "SAPIEN",
            "SATS",
            "SC",
            "SCA",
            "SCR",
            "SCRT",
            "SD",
            "SEI",
            "SFP",
            "SHELL",
            "SHIB",
            "SIGN",
            "SIREN",
            "SKATE",
            "SKL",
            "SKY",
            "SKYAI",
            "SLP",
            "SNT",
            "SNX",
            "SOL",
            "SOLV",
            "SOMI",
            "SONIC",
            "SOON",
            "SOPH",
            "SPELL",
            "SPK",
            "SPX",
            "SPYX",
            "SQD",
            "SSV",
            "STBL",
            "STEEM",
            "STG",
            "STO",
            "STORJ",
            "STRK",
            "STX",
            "SUI",
            "SUN",
            "SUNDOG",
            "SUPER",
            "SUSHI",
            "SWARMS",
            "SWEAT",
            "SWELL",
            "SWTCH",
            "SXP",
            "SXT",
            "SYN",
            "SYRUP",
            "SYS",
            "T",
            "TA",
            "TAG",
            "TAI",
            "TAIKO",
            "TAKE",
            "TANSSI",
            "TAO",
            "THE",
            "THETA",
            "TIA",
            "TLM",
            "TNSR",
            "TOKEN",
            "TON",
            "TOSHI",
            "TOWNS",
            "TQQQX",
            "TRB",
            "TREE",
            "TRU",
            "TRUMP",
            "TRX",
            "TSLAX",
            "TSTBSC",
            "TURBO",
            "TURTLE",
            "TUT",
            "TWT",
            "U",
            "UB",
            "UMA",
            "UNI",
            "USDC",
            "USELESS",
            "USTC",
            "USUAL",
            "VANA",
            "VANRY",
            "VELO",
            "VELODROME",
            "VELVET",
            "VET",
            "VFY",
            "VIC",
            "VINE",
            "VIRTUAL",
            "VOXEL",
            "VTHO",
            "VVV",
            "W",
            "WAL",
            "WAVES",
            "WAXP",
            "WCT",
            "WIF",
            "WLD",
            "WLFI",
            "WOO",
            "X",
            "XAI",
            "XAN",
            "XAUT",
            "XCH",
            "XCN",
            "XDC",
            "XION",
            "XLM",
            "XNO",
            "XNY",
            "XPIN",
            "XPL",
            "XRP",
            "XTZ",
            "XVS",
            "YALA",
            "YB",
            "YFI",
            "YGG",
            "YZY",
            "ZBCN",
            "ZBT",
            "ZEREBRO",
            "ZETA",
            "ZEUS",
            "ZIL",
            "ZK",
            "ZKC",
            "ZKJ",
            "ZORA",
            "ZRC",
            "ZRO",
            "ZRX"
        ]
    }
    // Kucoin: {
    //     spot: [
    //         "0G",
    //         "1INCH",
    //         "2Z",
    //         "A",
    //         "A2Z",
    //         "AAVE",
    //         "ACE",
    //         "ACH",
    //         "ACTSOL",
    //         "ACX",
    //         "ADA",
    //         "AERGO",
    //         "AERO",
    //         "AEVO",
    //         "AGLD",
    //         "AGT",
    //         "AI16Z",
    //         "AIN",
    //         "AIO",
    //         "AIOZ",
    //         "AIXBT",
    //         "AKE",
    //         "AKT",
    //         "ALGO",
    //         "ALICE",
    //         "ALPINE",
    //         "ALT",
    //         "ALU",
    //         "ANIME",
    //         "ANKR",
    //         "APE",
    //         "API3",
    //         "APT",
    //         "AR",
    //         "ARB",
    //         "ARIA",
    //         "ARKM",
    //         "ARPA",
    //         "ASP",
    //         "ASTER",
    //         "ASTR",
    //         "ATA",
    //         "ATH",
    //         "ATOM",
    //         "AUCTION",
    //         "AUDIO",
    //         "AVA",
    //         "AVAAI",
    //         "AVAIL",
    //         "AVAX",
    //         "AVNT",
    //         "AWE",
    //         "AXS",
    //         "B2",
    //         "B3",
    //         "BABY",
    //         "BAN",
    //         "BANANA",
    //         "BAND",
    //         "BARD",
    //         "BAS",
    //         "BAT",
    //         "BB",
    //         "BCH",
    //         "BERA",
    //         "BICO",
    //         "BIGTIME",
    //         "BIO",
    //         "BLAST",
    //         "BLUAI",
    //         "BLUR",
    //         "BMT",
    //         "BNB",
    //         "BOBA",
    //         "BOME",
    //         "BONK",
    //         "BR",
    //         "BRETT",
    //         "BROCCOLI",
    //         "BSV",
    //         "BTC",
    //         "BTR",
    //         "BULLA",
    //         "C",
    //         "C98",
    //         "CAKE",
    //         "CAMP",
    //         "CARV",
    //         "CAT",
    //         "CATI",
    //         "CELO",
    //         "CELR",
    //         "CETUS",
    //         "CFX",
    //         "CGPT",
    //         "CHEEMS",
    //         "CHILLGUY",
    //         "CHR",
    //         "CHZ",
    //         "CKB",
    //         "CLO",
    //         "CLOUD",
    //         "COMP",
    //         "COOKIE",
    //         "COTI",
    //         "COW",
    //         "CPOOL",
    //         "CRO",
    //         "CROSS",
    //         "CRV",
    //         "CTC",
    //         "CTSI",
    //         "CVC",
    //         "CVX",
    //         "CYBER",
    //         "D",
    //         "DASH",
    //         "DBR",
    //         "DEEP",
    //         "DEGEN",
    //         "DEGO",
    //         "DENT",
    //         "DEXE",
    //         "DGB",
    //         "DIA",
    //         "DMC",
    //         "DODO",
    //         "DOGE",
    //         "DOGS",
    //         "DOLO",
    //         "DOOD",
    //         "DOT",
    //         "DRIFT",
    //         "DUCK",
    //         "DUSK",
    //         "DYDX",
    //         "DYM",
    //         "EDEN",
    //         "EDU",
    //         "EGLD",
    //         "EIGEN",
    //         "ENA",
    //         "ENJ",
    //         "ENS",
    //         "ENSO",
    //         "EPIC",
    //         "EPT",
    //         "ERA",
    //         "ES",
    //         "ETC",
    //         "ETH",
    //         "ETHFI",
    //         "ETHW",
    //         "EUL",
    //         "F",
    //         "FARTCOIN",
    //         "FET",
    //         "FF",
    //         "FIDA",
    //         "FIL",
    //         "FLK",
    //         "FLOCK",
    //         "FLOKI",
    //         "FLOW",
    //         "FLR",
    //         "FLUX",
    //         "FORTH",
    //         "FRAG",
    //         "FTT",
    //         "FUEL",
    //         "FWOG",
    //         "FXS",
    //         "G",
    //         "GAS",
    //         "GIGGLE",
    //         "GLM",
    //         "GLMR",
    //         "GMT",
    //         "GMX",
    //         "GOAT",
    //         "GORK",
    //         "GPS",
    //         "GRASS",
    //         "GRIFFAIN",
    //         "GRT",
    //         "GTC",
    //         "GUN",
    //         "H",
    //         "HAEDAL",
    //         "HANA",
    //         "HBAR",
    //         "HEI",
    //         "HFT",
    //         "HIFI",
    //         "HIGH",
    //         "HIPPO",
    //         "HMSTR",
    //         "HNT",
    //         "HOLO",
    //         "HOME",
    //         "HSK",
    //         "HUMA",
    //         "HYPE",
    //         "HYPER",
    //         "ICNT",
    //         "ICP",
    //         "ICX",
    //         "ID",
    //         "IKA",
    //         "ILV",
    //         "IMX",
    //         "IN",
    //         "INIT",
    //         "INJ",
    //         "IO",
    //         "IOST",
    //         "IOTA",
    //         "IOTX",
    //         "IP",
    //         "J",
    //         "JASMY",
    //         "JELLYJELLY",
    //         "JST",
    //         "JTO",
    //         "JUP",
    //         "K",
    //         "KAIA",
    //         "KAITO",
    //         "KAS",
    //         "KAVA",
    //         "KCS",
    //         "KDA",
    //         "KERNEL",
    //         "KGEN",
    //         "KMNO",
    //         "KNC",
    //         "KOMA",
    //         "KSM",
    //         "LA",
    //         "LAB",
    //         "LDO",
    //         "LIGHT",
    //         "LINEA",
    //         "LINK",
    //         "LISTA",
    //         "LOOKS",
    //         "LPT",
    //         "LQTY",
    //         "LRC",
    //         "LSK",
    //         "LTC",
    //         "LUMIA",
    //         "LUNA",
    //         "LUNC",
    //         "LYN",
    //         "MAGIC",
    //         "MAJOR",
    //         "MANA",
    //         "MANTA",
    //         "MASK",
    //         "MAV",
    //         "MAVIA",
    //         "ME",
    //         "MELANIA",
    //         "MEME",
    //         "MEMEFI",
    //         "MERL",
    //         "METIS",
    //         "MEW",
    //         "MILK",
    //         "MINA",
    //         "MIRA",
    //         "MNT",
    //         "MOCA",
    //         "MOG",
    //         "MOODENG",
    //         "MORPHO",
    //         "MOVE",
    //         "MOVR",
    //         "MTL",
    //         "MUBARAK",
    //         "MYRO",
    //         "NAKA",
    //         "NAVX",
    //         "NC",
    //         "NEAR",
    //         "NEIRO",
    //         "NEIROCTO",
    //         "NEO",
    //         "NEWT",
    //         "NFP",
    //         "NIL",
    //         "NKN",
    //         "NMR",
    //         "NODE",
    //         "NOM",
    //         "NOT",
    //         "NTRN",
    //         "NXPC",
    //         "OGN",
    //         "OM",
    //         "ONDO",
    //         "ONE",
    //         "ONT",
    //         "OP",
    //         "OPEN",
    //         "ORBS",
    //         "ORCA",
    //         "ORDER",
    //         "ORDI",
    //         "OXT",
    //         "P",
    //         "PARTI",
    //         "PAXG",
    //         "PEAQ",
    //         "PENDLE",
    //         "PENGU",
    //         "PEOPLE",
    //         "PEPE",
    //         "PERP",
    //         "PHA",
    //         "PIXEL",
    //         "PLUME",
    //         "PNUT",
    //         "POL",
    //         "POLYX",
    //         "PONKE",
    //         "POPCAT",
    //         "PORTAL",
    //         "PORTALS",
    //         "PRCL",
    //         "PROM",
    //         "PROMPT",
    //         "PROVE",
    //         "PTB",
    //         "PUFFER",
    //         "PUMP",
    //         "PUNDIX",
    //         "PYTH",
    //         "Q",
    //         "QNT",
    //         "QTUM",
    //         "QUICK",
    //         "RATS",
    //         "RAY",
    //         "RDNT",
    //         "RECALL",
    //         "REDSTONE",
    //         "RENDER",
    //         "RESOLV",
    //         "REZ",
    //         "RFC",
    //         "RLC",
    //         "ROAM",
    //         "RONIN",
    //         "ROSE",
    //         "RPL",
    //         "RSR",
    //         "RUNE",
    //         "RVN",
    //         "RVV",
    //         "S",
    //         "SAFE",
    //         "SAHARA",
    //         "SAND",
    //         "SAPIEN",
    //         "SATS",
    //         "SCA",
    //         "SCR",
    //         "SCRT",
    //         "SD",
    //         "SEI",
    //         "SERAPH",
    //         "SFP",
    //         "SHELL",
    //         "SHIB",
    //         "SIGN",
    //         "SIREN",
    //         "SKATE",
    //         "SKL",
    //         "SKY",
    //         "SLP",
    //         "SNX",
    //         "SOL",
    //         "SOLAYER",
    //         "SOLV",
    //         "SOMI",
    //         "SONIC",
    //         "SOON",
    //         "SOPH",
    //         "SPK",
    //         "SPX",
    //         "SQD",
    //         "SSV",
    //         "STBL",
    //         "STG",
    //         "STO",
    //         "STORJ",
    //         "STRK",
    //         "STX",
    //         "SUI",
    //         "SUN",
    //         "SUNDOG",
    //         "SUPER",
    //         "SUPRA",
    //         "SUSHI",
    //         "SWARMS",
    //         "SWEAT",
    //         "SWELL",
    //         "SWTCH",
    //         "SXP",
    //         "SXT",
    //         "SYN",
    //         "SYRUP",
    //         "SYS",
    //         "T",
    //         "TAI",
    //         "TAIKO",
    //         "TAO",
    //         "THETA",
    //         "TIA",
    //         "TLM",
    //         "TNSR",
    //         "TOKEN",
    //         "TON",
    //         "TOSHI",
    //         "TOWNS",
    //         "TRB",
    //         "TREE",
    //         "TRU",
    //         "TRUMP",
    //         "TRUTH",
    //         "TRX",
    //         "TST",
    //         "TSTBSC",
    //         "TURBO",
    //         "TURTLE",
    //         "TUT",
    //         "TWT",
    //         "U",
    //         "UB",
    //         "UMA",
    //         "UNI",
    //         "USDC",
    //         "USELESS",
    //         "USTC",
    //         "USUAL",
    //         "VANA",
    //         "VANRY",
    //         "VELO",
    //         "VELVET",
    //         "VET",
    //         "VFY",
    //         "VINE",
    //         "VIRTUAL",
    //         "VOXEL",
    //         "VRA",
    //         "VTHO",
    //         "VVV",
    //         "W",
    //         "WAL",
    //         "WAVES",
    //         "WAXP",
    //         "WCT",
    //         "WIF",
    //         "WILD",
    //         "WLD",
    //         "WLFI",
    //         "WOO",
    //         "X",
    //         "XAI",
    //         "XAN",
    //         "XAUT",
    //         "XCH",
    //         "XCN",
    //         "XDC",
    //         "XEC",
    //         "XEM",
    //         "XION",
    //         "XLM",
    //         "XMR",
    //         "XNO",
    //         "XNY",
    //         "XPIN",
    //         "XPL",
    //         "XRP",
    //         "XTZ",
    //         "YB",
    //         "YFI",
    //         "YGG",
    //         "YZY",
    //         "ZBCN",
    //         "ZBT",
    //         "ZEC",
    //         "ZEN",
    //         "ZEREBRO",
    //         "ZETA",
    //         "ZEUS",
    //         "ZIL",
    //         "ZK",
    //         "ZKC",
    //         "ZKJ",
    //         "ZORA",
    //         "ZRC",
    //         "ZRO",
    //         "ZRX"
    //     ],
    //     future: [
    //         "0G",
    //         "1000CHEEMS",
    //         "1INCH",
    //         "1MBABYDOGE",
    //         "2Z",
    //         "A",
    //         "A2Z",
    //         "AAVE",
    //         "ACE",
    //         "ACH",
    //         "ACTSOL",
    //         "ADA",
    //         "AERGO",
    //         "AERO",
    //         "AEVO",
    //         "AGI",
    //         "AGLD",
    //         "AGT",
    //         "AI",
    //         "AI16Z",
    //         "AIA",
    //         "AIN",
    //         "AIO",
    //         "AIOT",
    //         "AIXBT",
    //         "AKE",
    //         "ALCH",
    //         "ALGO",
    //         "ALICE",
    //         "ALPINE",
    //         "ALU",
    //         "ANIME",
    //         "ANKR",
    //         "APE",
    //         "API3",
    //         "APT",
    //         "AR",
    //         "ARB",
    //         "ARIA",
    //         "ARK",
    //         "ARKM",
    //         "ARPA",
    //         "ASP",
    //         "ASR",
    //         "ASTER",
    //         "ASTR",
    //         "ATH",
    //         "ATOM",
    //         "AUCTION",
    //         "AUDIO",
    //         "AVA",
    //         "AVAAI",
    //         "AVAIL",
    //         "AVAX",
    //         "AVNT",
    //         "AWE",
    //         "AXL",
    //         "AXS",
    //         "B",
    //         "B2",
    //         "B3",
    //         "BABY",
    //         "BAN",
    //         "BANANA",
    //         "BANANAS31",
    //         "BAND",
    //         "BARD",
    //         "BAS",
    //         "BAT",
    //         "BB",
    //         "BCH",
    //         "BDXN",
    //         "BEL",
    //         "BERA",
    //         "BIGTIME",
    //         "BIO",
    //         "BLAST",
    //         "BLESS",
    //         "BLUAI",
    //         "BLUR",
    //         "BMT",
    //         "BNB",
    //         "BNT",
    //         "BOME",
    //         "BR",
    //         "BRETT",
    //         "BSV",
    //         "BTC",
    //         "BTR",
    //         "C",
    //         "C98",
    //         "CAKE",
    //         "CAMP",
    //         "CARV",
    //         "CATI",
    //         "CELO",
    //         "CELR",
    //         "CETUS",
    //         "CFX",
    //         "CGPT",
    //         "CHILLGUY",
    //         "CHR",
    //         "CHZ",
    //         "CKB",
    //         "CLO",
    //         "COAI",
    //         "COMP",
    //         "COOKIE",
    //         "COTI",
    //         "COW",
    //         "CRO",
    //         "CROSS",
    //         "CRV",
    //         "CTC",
    //         "CTSI",
    //         "CUDIS",
    //         "CVC",
    //         "CVX",
    //         "CYBER",
    //         "D",
    //         "DASH",
    //         "DEEP",
    //         "DEGEN",
    //         "DENT",
    //         "DMC",
    //         "DODO",
    //         "DOG",
    //         "DOGE",
    //         "DOGS",
    //         "DOLO",
    //         "DOOD",
    //         "DOT",
    //         "DRIFT",
    //         "DUSK",
    //         "DYDX",
    //         "DYM",
    //         "EDEN",
    //         "EDU",
    //         "EGLD",
    //         "EIGEN",
    //         "ENA",
    //         "ENJ",
    //         "ENS",
    //         "ENSO",
    //         "EPT",
    //         "ERA",
    //         "ES",
    //         "ESPORTS",
    //         "ETC",
    //         "ETH",
    //         "ETHFI",
    //         "EUL",
    //         "EVAA",
    //         "F",
    //         "FARTCOIN",
    //         "FET",
    //         "FF",
    //         "FIL",
    //         "FIS",
    //         "FLM",
    //         "FLOCK",
    //         "FLOKI",
    //         "FLOW",
    //         "FLUID",
    //         "FLUX",
    //         "FORM",
    //         "FORTH",
    //         "FRAG",
    //         "FTT",
    //         "FUEL",
    //         "FUN",
    //         "FXS",
    //         "G",
    //         "GALA",
    //         "GAS",
    //         "GIGGLE",
    //         "GLMR",
    //         "GMT",
    //         "GMX",
    //         "GOAT",
    //         "GORK",
    //         "GPS",
    //         "GRASS",
    //         "GRIFFAIN",
    //         "GRT",
    //         "GTC",
    //         "GUN",
    //         "H",
    //         "HAEDAL",
    //         "HANA",
    //         "HBAR",
    //         "HEI",
    //         "HEMI",
    //         "HFT",
    //         "HIGH",
    //         "HIPPO",
    //         "HIVE",
    //         "HMSTR",
    //         "HOLO",
    //         "HOME",
    //         "HOOK",
    //         "HSK",
    //         "HUMA",
    //         "HYPE",
    //         "HYPER",
    //         "ICNT",
    //         "ICP",
    //         "ICX",
    //         "ID",
    //         "IDOL",
    //         "IKA",
    //         "ILV",
    //         "IMX",
    //         "IN",
    //         "INIT",
    //         "INJ",
    //         "IO",
    //         "IOTA",
    //         "IOTX",
    //         "IP",
    //         "J",
    //         "JASMY",
    //         "JELLYJELLY",
    //         "JOE",
    //         "JTO",
    //         "JUP",
    //         "KAIA",
    //         "KAITO",
    //         "KAS",
    //         "KAVA",
    //         "KCS",
    //         "KDA",
    //         "KERNEL",
    //         "KGEN",
    //         "KNC",
    //         "KOMA",
    //         "KSM",
    //         "LA",
    //         "LAB",
    //         "LDO",
    //         "LIGHT",
    //         "LINEA",
    //         "LINK",
    //         "LISTA",
    //         "LOOKS",
    //         "LPT",
    //         "LQTY",
    //         "LRC",
    //         "LTC",
    //         "LUNA",
    //         "LUNC",
    //         "LYN",
    //         "M",
    //         "MAGIC",
    //         "MAJOR",
    //         "MANA",
    //         "MANTA",
    //         "MASK",
    //         "MAV",
    //         "MAVIA",
    //         "MBOX",
    //         "MDT",
    //         "ME",
    //         "MELANIA",
    //         "MEME",
    //         "MEMEFI",
    //         "MERL",
    //         "METIS",
    //         "MEW",
    //         "MILK",
    //         "MINA",
    //         "MIRA",
    //         "MITO",
    //         "MLN",
    //         "MOCA",
    //         "MOODENG",
    //         "MORPHO",
    //         "MOVE",
    //         "MOVR",
    //         "MTL",
    //         "MUBARAK",
    //         "MYRO",
    //         "MYX",
    //         "NAKA",
    //         "NAORIS",
    //         "NC",
    //         "NEAR",
    //         "NEIROCTO",
    //         "NEO",
    //         "NEWT",
    //         "NFP",
    //         "NIL",
    //         "NKN",
    //         "NMR",
    //         "NOM",
    //         "NOT",
    //         "NTRN",
    //         "NXPC",
    //         "OBOL",
    //         "OG",
    //         "OGN",
    //         "OM",
    //         "ONDO",
    //         "ONE",
    //         "ONT",
    //         "OP",
    //         "OPEN",
    //         "ORBS",
    //         "ORCA",
    //         "ORDER",
    //         "ORDI",
    //         "OXT",
    //         "PARTI",
    //         "PAXG",
    //         "PENDLE",
    //         "PENGU",
    //         "PEOPLE",
    //         "PEPE",
    //         "PERP",
    //         "PHA",
    //         "PHB",
    //         "PIXEL",
    //         "PLUME",
    //         "PNUT",
    //         "POL",
    //         "POLYX",
    //         "PONKE",
    //         "POPCAT",
    //         "PORTAL",
    //         "POWR",
    //         "PRCL",
    //         "PROM",
    //         "PROMPT",
    //         "PROVE",
    //         "PTB",
    //         "PUFFER",
    //         "PUMP",
    //         "PYTH",
    //         "Q",
    //         "QNT",
    //         "QTUM",
    //         "RARE",
    //         "RAY",
    //         "RDNT",
    //         "RECALL",
    //         "REDSTONE",
    //         "RENDER",
    //         "RESOLV",
    //         "REZ",
    //         "RFC",
    //         "RIF",
    //         "ROAM",
    //         "RON",
    //         "ROSE",
    //         "RSR",
    //         "RUNE",
    //         "RVN",
    //         "RVV",
    //         "S",
    //         "SAGA",
    //         "SAHARA",
    //         "SAND",
    //         "SAPIEN",
    //         "SCR",
    //         "SEI",
    //         "SFP",
    //         "SHELL",
    //         "SHIB",
    //         "SIGN",
    //         "SIREN",
    //         "SKATE",
    //         "SKL",
    //         "SKY",
    //         "SKYAI",
    //         "SNX",
    //         "SOL",
    //         "SOLAYER",
    //         "SOLV",
    //         "SOMI",
    //         "SONIC",
    //         "SOON",
    //         "SOPH",
    //         "SPELL",
    //         "SPK",
    //         "SPX",
    //         "SSV",
    //         "STBL",
    //         "STEEM",
    //         "STG",
    //         "STO",
    //         "STORJ",
    //         "STRK",
    //         "STX",
    //         "SUI",
    //         "SUN",
    //         "SUNDOG",
    //         "SUPER",
    //         "SUPRA",
    //         "SUSHI",
    //         "SWARMS",
    //         "SWELL",
    //         "SXP",
    //         "SXT",
    //         "SYRUP",
    //         "T",
    //         "TA",
    //         "TAG",
    //         "TAIKO",
    //         "TAKE",
    //         "TANSSI",
    //         "TAO",
    //         "THE",
    //         "THETA",
    //         "TIA",
    //         "TNSR",
    //         "TOKEN",
    //         "TON",
    //         "TOSHI",
    //         "TOWNS",
    //         "TRB",
    //         "TREE",
    //         "TRU",
    //         "TRUMP",
    //         "TRUTH",
    //         "TRX",
    //         "TSTBSC",
    //         "TURBO",
    //         "TURTLE",
    //         "TUT",
    //         "TWT",
    //         "U",
    //         "UB",
    //         "UMA",
    //         "UNI",
    //         "USDC",
    //         "USELESS",
    //         "USTC",
    //         "USUAL",
    //         "VANA",
    //         "VANRY",
    //         "VELVET",
    //         "VET",
    //         "VFY",
    //         "VIC",
    //         "VINE",
    //         "VIRTUAL",
    //         "VOXEL",
    //         "VRA",
    //         "VVV",
    //         "W",
    //         "WAL",
    //         "WAVES",
    //         "WAXP",
    //         "WCT",
    //         "WIF",
    //         "WILD",
    //         "WLD",
    //         "WLFI",
    //         "WOO",
    //         "XAI",
    //         "XAN",
    //         "XCN",
    //         "XEC",
    //         "XEM",
    //         "XLM",
    //         "XMR",
    //         "XNY",
    //         "XPIN",
    //         "XPL",
    //         "XRP",
    //         "XTZ",
    //         "XVG",
    //         "XVS",
    //         "YALA",
    //         "YB",
    //         "YFI",
    //         "YGG",
    //         "YZY",
    //         "ZBT",
    //         "ZEC",
    //         "ZEN",
    //         "ZEREBRO",
    //         "ZETA",
    //         "ZEUS",
    //         "ZIL",
    //         "ZK",
    //         "ZKC",
    //         "ZKJ",
    //         "ZORA",
    //         "ZRC",
    //         "ZRO",
    //         "ZRX"
    //     ]
    // }
}